stages:
  - build
  - test
  - deploy

buildtest-node:
  image: node:latest
  stage: build
  script:
    - apt-get update -qy
    - npm install

docker-test:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script:
  - docker login registry.gitlab.com -u wilsonlo1997@gmail.com -p Vi26151851@
  - docker build -t registry.gitlab.com/asiabots/wilson/line_bot_api .
  - docker run -d -p 80:80 registry.gitlab.com/asiabots/wilson/cantonese-nlp

docker-deploy:
  image: docker:latest
  services:
      - docker:dind
  stage: deploy
  script:
      - docker login registry.gitlab.com -u wilsonlo1997@gmail.com -p Vi26151851@
      - docker build -t registry.gitlab.com/asiabots/wilson/line_bot_api .
      - docker push registry.gitlab.com/asiabots/wilson/line_bot_api
  only:
      - master